### ISSUE TITLE
USER STORY: Score Tracking

### ISSUE THREAD

**Issue by deonmoodley** [Indk0/QuizNinja-Hackathon-1#8]
As a user
I want to see my current score while taking the quiz
So that I can track my progress

Acceptance Criteria:

- [x] 	The score should be displayed and updated in real-time as the user answers each question.
- [x] 	The scoring panel should be unobtrusive but visible.
- [x] 	Users should be able to view their final score at the end of the quiz.
